image: "python:3.7"

before_script:
  - python --version
  - pip install pytest

stages:
  - PytestTest

pytestTest:
  stage: PytestTest
  script:
  - pytest src/test/ #when running test on pytest in a directory, the test filename should start with "test_"
  - echo "Pytest test succeeded"
